### PR TITLE
add header image blue theme [Resources]

### PR DESCRIPTION
**Pull request by tstreamDOTh**
Modified to blue theme for header image for the meetup page.

### CODE REVIEW

**Comment by tstreamDOTh** [comment]
@PareshMayani  does this work for you?

**Comment by PareshMayani** [comment]
@tstreamDOTh it looks perfect to me. Sorry for sharing it lately but if you can make this small correction then it will make it a complete one and we will start using it. Change is: We want "GDG Ahmedabad" text on banner and so we just want to remove "Google Developer Group" text

**Comment by tstreamDOTh** [comment]
@PareshMayani No issues,  I have made the changes. Let me know if it works out for you.

**Comment by PareshMayani** [comment]
@tstreamDOTh thanks for the correction. I just tried uploading on meetup page to check how it looks.

I have found 2 things:
- Banner images look best at 960px wide by 150px high
- How about increasing font size of GDG Ahmedabad? You suggest as you better know.

**Comment by tstreamDOTh** [comment]
@PareshMayani  Have increased the font size, though the image was also having the same dimensions as mentioned in meetup guidelines.

**Comment by PareshMayani** [comment]
@tstreamDOTh  thanks it looks good. 

Thank you for putting efforts and sharing excellent banner image for the GDG Ahmedabad community, we really appreciate it.

Second, thank you keeping older images as well, we may use it as well!

Also, if you can share a PSD file then it would be helpful to us in using it for any event banner or somewhere else!

**Comment by PareshMayani** [comment]
@tstreamDOTh it looks excellent on our meetup page https://www.meetup.com/GDG-Ahmedabad/. Really appreciate your contribution and efforts you have put for it.

**Comment by tstreamDOTh** [comment]
@PareshMayani  Always welcome!  I have added the project file too. Can you merge the pull?

**Comment by PareshMayani** [comment]
@tstreamDOTh I don't see PSD files. Can you please re-check and confirm?

**Comment by tstreamDOTh** [comment]
Sure, I added the .ai file (illustrator). Please cross check and merge.

**Comment by PareshMayani** [comment]
Thanks @tstreamDOTh for getting our meetup page a new look. Looking forward for more contribution in future!

**Pull request merged**
